<a href="https://colab.research.google.com/github/seoho0529/numpy/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# 배열 연산
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.arange(5,9).reshape((2,2))  # 5부터9까지 , 2행2열
y = y.astype(np.float32)  # astype을 통해 형변환 가능
print(x, x.dtype)
print(y, y.dtype)

print(x + y)  # -, *, /
print(np.add(x, y))  # substract, multiply, divide

# 참고 : 연산 속도
big_arr = np.random.rand(1000000)
print(big_arr)
%timeit sum(big_arr)   # python함수 : sum

[[1. 2.]
 [3. 4.]] float64
[[5. 6.]
 [7. 8.]] float32
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[9.75385726e-01 9.33680541e-01 7.45905918e-01 ... 4.51309592e-01
 1.16639619e-04 3.26227531e-01]
81.3 ms ± 19.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit np.sum(big_arr)  # numpy함수 : sum
# python함수보다 numpy함수의 연산 속도가 더 빠르다.

217 µs ± 4.78 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [16]:
# 벡터연산(내적)
v = np.array([9, 10])
w = np.array([11, 12])
print(v * w)         # 일반 곱셈,, [ 99 120]
print(v.dot(w))      # 219 = (9*11) + (10*12)
print(np.dot(v, w))  # 219
print(x.dot(v))      # [29 = 1*9 + 2*10. 67 = 3*9 + 4*10.]
print(x.dot(y))

[ 99 120]
219
219
[29. 67.]
[[19. 22.]
 [43. 50.]]


In [23]:
# numpy는 연산을 위한 함수들을 제공한다.
print(np.sum(x))          # 모든 요소들의 합 - 10.0
print(np.sum(x, axis=0))  # 열에 대한 합 - [4. 6.]
print(np.sum(x, axis=1))  # 행에 대한 합 - [3. 7.]
print(np.mean(x))     # 평균
print(np.argmax(x))   # 요소 중 가장 큰 값의 순번(최대값의 인덱스번호)
print(np.sqrt(x))
print(np.cumsum(x))   # 누적합

10.0
[4. 6.]
[3. 7.]
2.5
3
[[1.         1.41421356]
 [1.73205081 2.        ]]
[ 1.  3.  6. 10.]


In [28]:
names = np.array(['tom','james','tom','oscar'])
names2 = np.array(['tom','page','john'])
print(np.unique(names))  # 중복 배제
print(np.intersect1d(names, names2))  # 교집합 - 중복 허용 X
print(np.intersect1d(names, names2, assume_unique=True)) # 교집합 - 중복 허용
print(np.union1d(names, names2))  # 합집합

['james' 'oscar' 'tom']
['tom']
['tom' 'tom']
['james' 'john' 'oscar' 'page' 'tom']


In [30]:
# 전치(transpose) - 행렬의 위치를 바꿈
print(x)
print(x.T)

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]


In [44]:
# Broadcasting : 크기가 다른 배열 간의 연산 시, 작은 배열은 큰 배열에 맞춰져 연산한다.
x = np.arange(1, 10).reshape(3,3)
print(x)  # 3행3열
print()
y = np.array([1,0,1])
print(y)  # 1행3열
print()
z = np.empty_like(x)
#print(z)

print()
for i in range(3):
  z[i] = x[i] + y
print(z)

print()
kbs = x + y
print(kbs)  # for문을 돌리지않고 그냥 행렬 더하기 해도 값이 같음

print('배열 자료를 파일 i/o')
print(x)
np.savetxt('my.txt', x)
print()
my2 = np.loadtxt('my.txt')
print(my2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 0 1]


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
배열 자료를 파일 i/o
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
