<a href="https://colab.research.google.com/github/seoho0529/numpy/blob/main/numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# 배열에 행 또는 열 추가, 삭제
import numpy as np

aa = np.eye(3)
print(aa)

bb = np.c_[aa, aa[2]]  # 열 추가 : c_
print(bb)

cc = np.r_[aa, [aa[2]]] # 행 추가 : r_
print(cc)

print('열 추가를 이용해 행을 열로 변환이 가능하다.')
a = np.array([1,2,3])
print(np.c_[a])  # 1행 3열의 위치가 바뀜
print(a.reshape((3,1)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
열 추가를 이용해 행을 열로 변환이 가능하다.
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [11]:
print(a)
b = np.append(a, [4,5])
print(b)
c = np.insert(a, 0, [6,7])  #a의 인덱스 0번에 6,7을 삽입
print(c)
d = np.delete(a, 1)
print(d)

[1 2 3]
[1 2 3 4 5]
[6 7 1 2 3]
[1 3]


In [16]:
aa = np.arange(1, 10).reshape(3,3)
print(aa)
print(np.insert(aa, 1, 99))  # 1번째에 99 추가, axis가 없으면 차원 축소
print(np.insert(aa, 1, 99, axis=0))  # 행 기준, axis가 있으면 차원 유지
print(np.insert(aa, 1, 99, axis=1))  # 열 기준

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1 99  2  3  4  5  6  7  8  9]
[[ 1  2  3]
 [99 99 99]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 99  2  3]
 [ 4 99  5  6]
 [ 7 99  8  9]]


In [20]:
bb = np.arange(11, 20).reshape(3,3)
print(bb)

cc = np.append(aa, bb)
print(cc)  # axis가 없어서 차원이 축소됨

cc = np.append(aa, bb, axis=0)  # 행
print(cc)

cc = np.append(aa, bb, axis=1)  # 열
print(cc)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [24]:
print(aa)
print(np.delete(aa,1))
print(np.delete(aa,1,axis=0))
print(np.delete(aa,1,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 3 4 5 6 7 8 9]
[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]


In [32]:
# 조건 연산 : where(조건, 참, 거짓)
x = np.array([1,2,3])
y = np.array([4,5,6])
conditionData = np.array([True, False, True])
result = np.where(conditionData, x, y)
print(result)

aa = np.where(x >= 2)
print(aa, x[aa])
print(np.where(x >= 2, 'T','F'))
print(np.where(x >= 2, x,x+100))
print()
bb = np.random.randn(4, 4)  # 정규분포를 따르는 난수 생성
print(bb)
print(np.where(bb > 0, 10, bb))

[1 5 3]
(array([1, 2]),) [2 3]
['F' 'T' 'T']
[101   2   3]

[[ 1.134561    0.45727766  0.4619791  -0.81731722]
 [ 0.05590379  1.29147556  0.09499811 -0.5748145 ]
 [ 0.42309278  0.68484157 -0.37413196 -1.03369077]
 [ 0.61543444 -0.44121789 -0.05110512 -0.70251983]]
[[10.         10.         10.         -0.81731722]
 [10.         10.         10.         -0.5748145 ]
 [10.         10.         -0.37413196 -1.03369077]
 [10.         -0.44121789 -0.05110512 -0.70251983]]


In [39]:
print(x)
print(y)
mbc = np.concatenate([x,y])  # 배열 결합
print(mbc)

x1, x2 = np.split(mbc, 2)  # mbc를 두개로 분리
print(x1)
print(x2)

a = np.arange(1,17).reshape(4,4)
print(a)
print()

x1,x2 = np.hsplit(a,2)  # 좌,우로 분리
print(x1)
print(x2)
print()

x1,x2 = np.vsplit(a,2)  # 상, 하로 분리
print(x1)
print(x2)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [55]:
# sampline : 표본 추출
li = np.array([1,2,3,4,5,6,7])

# 복원 추출
for _ in range(5):
  print(li[np.random.randint(0, len(li) - 1)], end=' ')

print()
# 비복원 추출
import random
print(random.sample(list(li), k=5))
print(random.sample(range(1,46), k=6))
print()
print(list(np.random.choice(range(1,46), 6)))
print(list(np.random.choice(range(1,46), 6, replace=False)))  # 비복원
print(list(np.random.choice(range(1,46), 6, replace=True)))   # 복원 - 중복 허용
# numpy의 choice 함수와 python의 sample을 사용하면 복원, 비복원 추출이 가능

# 가중치를 부여한 랜덤추출
ar = 'air book cat desk e f god'
ar = ar.split(sep=' ')
print(ar)
print(np.random.choice(ar,3,p=[0.1, 0.1,0.1, 0.1,0.1, 0.1,0.4]))

1 4 4 2 1 
[4, 5, 2, 7, 6]
[5, 24, 21, 1, 39, 25]

[43, 25, 22, 38, 38, 8]
[38, 4, 9, 20, 43, 31]
[21, 13, 36, 21, 20, 10]
['air', 'book', 'cat', 'desk', 'e', 'f', 'god']
['god' 'god' 'god']
