<a href="https://colab.research.google.com/github/seoho0529/numpy/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
!uname -a
!cat /etc/*release
!man

Linux 29f01a2bf7a1 5.15.120+ #1 SMP Wed Aug 30 11:19:59 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, including manpages, you can run the 'unminimize'
command. You will still need to ensure the 'man-db' package is installed.


In [15]:
grades = [1,3,-2,4]

def grades_sum(grades):
  tot=0
  for g in grades:
    tot += g
    return tot

def grades_avg(grades):
  tot = grades_sum(grades)
  ave = tot/len(grades)
  return ave

def grades_variance(grades):
  ave = grades_avg(grades)
  vari = 0
  for su in grades:
    vari += (su - ave) ** 2  # 편차 제곱의 합
    return vari / len(grades)  # 모집단으로 계산
    return vari / (len(grades) - 1) # 표본집단으로 계산(n-1)

def grades_std(grades):
  return grades_variance(grades) ** 0.5


In [17]:
print('합은', grades_sum(grades))
print('평균은', grades_avg(grades))
print('분산은', grades_variance(grades))
print('표준편차는', grades_std(grades))

import numpy as np
print('합은', np.sum(grades))
print('평균은', np.mean(grades), ' ', np.average(grades))
print('분산은', np.var(grades))
print('표준편차는', np.std(grades))

합은 1
평균은 0.25
분산은 0.140625
표준편차는 0.375
합은 6
평균은 1.5   1.5
분산은 5.25
표준편차는 2.29128784747792


In [22]:
#numpy모듈(라이브러리)
#다차원 배열 자료구조인 ndarray, 선형대수 계산, 벡터 연산, 미적분 등을 지원
import numpy as np
ss = ['tom','oscar','john',12,12.3]
print(ss, type(ss))
ss2 = np.array(ss) # list를 ndarray로 변환. 같은 타입으로 요소값이 구성. 상위 타입으로 변환 int -> float -> complex -> string
print(ss2, type(ss2))

['tom', 'oscar', 'john', 12, 12.3] <class 'list'>
['tom' 'oscar' 'john' '12' '12.3'] <class 'numpy.ndarray'>


In [28]:
# 메모리 비교(list vs ndarray)
# list
li = list(range(1, 10))
print(li)
print(id(li[0]), id(li[1]))  # 요소값 하나하나가 별도의 인스턴스이기 때문에 주소가 다름
print(li * 10)
for i in li:
  print(i * 10, end=' ')

print('\n')
# ndarray
num_arr = np.array(li)
print(num_arr)
print(id(num_arr[0]), id(num_arr[1]))
print(num_arr*10)  # 벡터 연산

[1, 2, 3, 4, 5, 6, 7, 8, 9]
135607487283440 135607487283472
[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
10 20 30 40 50 60 70 80 90 

[1 2 3 4 5 6 7 8 9]
135606215310224 135606215310224
[10 20 30 40 50 60 70 80 90]


In [30]:
a = np.array([1,2,3])  # 1차원 배열
print(a, type(a), a.dtype, a.shape, a.size)  # [1 2 3] <class 'numpy.ndarray'> int64 (3,) 3
print(a[0], a[2])
a[0] = 7
print(a)

[1 2 3] <class 'numpy.ndarray'> int64 (3,) 3
1 3
[7 2 3]


In [34]:
b = np.array([[1,2,3],[4,5,6]], dtype='float32') # 2차원 배열, 2행3열
print(b, type(a), b.dtype, b.shape, b.size)
print(b[0,0], b[0,2]) # 0행 0열 : 1, 0행 2열 ; 3
print(b[[0]])  # 0행 [[1,2,3]]

[[1. 2. 3.]
 [4. 5. 6.]] <class 'numpy.ndarray'> float32 (2, 3) 6
1.0 3.0
[[1. 2. 3.]]


In [37]:
c = np.zeros((2,2))  # 2행2열을 0으로 채우기
print(c)
d = np.ones((2,2)) # 2행 2열 1로 채우기
print(d)
e = np.full((2,2), 7) # 2행 2열 7로 채우기
print(e)
f = np.eye(3)  # 정방행렬 3행3열
print(f)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
np.random.seed(0)  # 난수 고
print(np.random.rand(5))  # 균등분포를 따르는 난수
print(np.random.randn(5)) # 정규분포를 따르는 난수

print(np.random.randint(10, size=6)) # 1차원 -- 벡터
print(np.random.randint(10, size=(3,4))) # 2차원 - 3행4열 -- 매트릭스
print(np.random.randint(10, size=(3,4,5))) # 3차원 - 3면 4행5열

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[-0.84272405  1.96992445  1.26611853 -0.50587654  2.54520078]
[5 9 8 9 4 3]
[[0 3 5 0]
 [2 3 8 1]
 [3 3 3 7]]
[[[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]

 [[4 3 4 4 8]
  [4 3 7 5 5]
  [0 1 5 9 3]
  [0 5 0 1 2]]]


In [52]:
# 인덱싱, 슬라이싱
a = np.array([1,2,3,4,5])
print(a)
print(a[0])
print(a[1:3])
print(a[1:5:2])

print()
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
print(b[:])
print(b[0,0])
print(b[[0]], b[0], b[0][0])  # 0행0열 :차원유지, 0행 출력 : b[0]:차원축소   # [[1 2 3 4]] [1 2 3 4] 1
print(b[1:, 0:2])

print()
c = b[:2, 1:3]  # sub array,, 원본 배열은 b가 가지고 있는
print(c)
print(c[0,0])
c[0,0] = 99
print(c)
print(b)

[1 2 3 4 5]
1
[2 3]
[2 4]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[1 2 3 4]] [1 2 3 4] 1
[[ 5  6]
 [ 9 10]]

[[2 3]
 [6 7]]
2
[[99  3]
 [ 6  7]]
[[ 1 99  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
