<a href="https://colab.research.google.com/github/seoho0529/numpy/blob/main/numpy3_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
# 정규분포를 따르는 난수를 이용하여 5행 4열 구조의 다차원 배열 객체를 생성하고, 각 행 단위로 합계, 최댓값을 구하시오.
# < 출력 결과 예시>
# 1행 합계   : 0.8621332497162859
# 1행 최댓값 : 0.3422690004932227
# 2행 합계   : -1.5039264306910727
# 2행 최댓값 : 0.44626169669315
# 3행 합계   : 2.2852559938172514
# 3행 최댓값 : 1.5507574553572447
import numpy as np
a = np.random.randn(5, 4)
print(a)
print()
print(np.sum(a, axis=1))
print(np.max(a, axis=1))
print()
i = 1
for r in a:
  print(str(i) + "행 합계 : ", r.sum())
  print(str(i) + "행 최댓값 : ", r.max())
  i += 1

[[ 2.741077    0.62092958  0.58511185  1.57757612]
 [ 1.5763332   1.19367318 -0.43643596 -1.32720928]
 [-0.94178015 -0.57272535  0.47818106  0.16046441]
 [-1.46567965 -0.82148512  1.56416593  0.11398234]
 [ 1.68776621 -0.2929744  -0.32896342  0.59455698]]

[ 5.52469455  1.00636114 -0.87586002 -0.6090165   1.66038537]
[2.741077   1.5763332  0.47818106 1.56416593 1.68776621]

1행 합계 :  5.524694547117168
1행 최댓값 :  2.741076999486644
2행 합계 :  1.006361137220119
2행 최댓값 :  1.5763331961632474
3행 합계 :  -0.8758600213152148
3행 최댓값 :  0.4781810638572198
4행 합계 :  -0.6090165034664229
4행 최댓값 :  1.5641659275807782
5행 합계 :  1.6603853675561941
5행 최댓값 :  1.687766208006596


In [57]:
# 문2-1) 6행 6열의 다차원 zero 행렬 객체를 생성한 후 다음과 같이 indexing 하시오.
b = np.zeros([6,6])
print(b)
# 조건1> 36개의 셀에 1~36까지 정수 채우기
b = np.arange(1, 37).reshape(6,6)
print(b)
# 조건2> 2번째 행 전체 원소 출력하기
print(b[1])
# 조건3> 5번째 열 전체 원소 출력하기
print(b[:,4])
# 조건4> 15~29 까지 아래 처럼 출력하기
c = b[2:5, 2:5]
print(c)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[ 7  8  9 10 11 12]
[ 5 11 17 23 29 35]
[[15 16 17]
 [21 22 23]
 [27 28 29]]


In [59]:
#  문2-2) 6행 4열의 다차원 zero 행렬 객체를 생성한 후 아래와 같이 처리하시오.
d = np.zeros([6,4])
print(d)
# 조건1> 20~100 사이의 난수 정수를 6개 발생시켜 각 행의 시작열에 난수 정수를 저장하고, 두 번째 열부터는 1씩 증가시켜 원소 저장하기
e = np.random.randint(20, 101, size=6)
for i in range(6):
    d[i, 0] = e[i]
    for j in range(1, 4):
        d[i, j] = d[i, j - 1] + 1
print(e)
# 조건2> 첫 번째 행에 1000, 마지막 행에 6000으로 요소값 수정하기
d[0, :] = 1000
d[-1, :] = 6000

print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[49 51 86 61 83 32]
[[1000. 1000. 1000. 1000.]
 [  51.   52.   53.   54.]
 [  86.   87.   88.   89.]
 [  61.   62.   63.   64.]
 [  83.   84.   85.   86.]
 [6000. 6000. 6000. 6000.]]


In [43]:
# step3 : unifunc 관련문제
x = np.random.normal(0,1,[4,5])
print(x)
print('평균 : ',np.mean(x))
print('합계 : ',np.sum(x))
print('표준편차 : ',np.sqrt(x))
print('분산 : ',np.var(x))
print('최댓값 : ',np.max(x))
print('최솟값 : ',np.min(x))
print('1사분위 수 : ',np.percentile(x,25))
print('2사분위 수 : ',np.percentile(x,50))
print('3사분위 수 : ',np.percentile(x,75))
print('요소값 누적합 : ',np.cumsum(x))

[[ 1.62991461  0.23166298  1.24228504  0.50622707  1.83874752]
 [-0.08992708  1.0185178   1.23274473  1.60518424 -0.66690596]
 [-0.04911282 -0.36920259  0.70044699  0.52989164  0.74137121]
 [ 1.71435281 -0.17920067  0.60255264  0.33183816  0.36746036]]
평균 :  0.6469424329930917
합계 :  12.938848659861835
표준편차 :  [[1.27668109 0.4813138  1.11457842 0.71149636 1.35600425]
 [       nan 1.00921643 1.11029038 1.26695866        nan]
 [       nan        nan 0.83692711 0.72793657 0.86102916]
 [1.30933296        nan 0.77624264 0.57605395 0.60618509]]
분산 :  0.5072865651609214
최댓값 :  1.8387475199093792
최솟값 :  -0.6669059609597813
1사분위 수 :  0.16146902515345246
2사분위 수 :  0.5662221412861146
3사분위 수 :  1.2351298073186636
요소값 누적합 :  [ 1.62991461  1.86157758  3.10386262  3.61008969  5.44883721  5.35891013
  6.37742793  7.61017266  9.21535689  8.54845093  8.49933811  8.13013552
  8.83058251  9.36047415 10.10184536 11.81619817 11.63699751 12.23955015
 12.5713883  12.93884866]


<ipython-input-43-56e5ca053a59>:6: RuntimeWarning: invalid value encountered in sqrt
  print('표준편차 : ',np.sqrt(x))
